import {
  REALM_IF_MIGRATION_NEEDED as ENV_REALM_IF_MIGRATION_NEEDED,
  REALM_SCHEME_VERSION as ENV_REALM_SCHEME_VERSION,
} from '@env';

export const REALM_IF_MIGRATION_NEEDED: boolean =
  ENV_REALM_IF_MIGRATION_NEEDED === 'true';
export const REALM_SCHEME_VERSION: number | undefined = ENV_REALM_SCHEME_VERSION
  ? parseInt(ENV_REALM_SCHEME_VERSION, 10)
  : undefined;
